export const playerData = [
  {
    id: 0,
    name: 'Player 1',
    color: 'red',
    img: 'fas fa-cat',
    controlledBy: 'ai',
    balance: 1500,
    position: 0,
    properties: [],
    inJail: false,
    doubleCount: 0,
    jailRoll :0,
    communityChestJailCard: false,
    chanceJailCard: false,
  },

  {
    id: 1,
    name: 'Player 2',
    color: 'orange',
    img: 'fas fa-dog',
    controlledBy: 'ai',
    balance: 1500,
    position: 0,
    properties: [],
    inJail: false,
    doubleCount: 0,
    jailRoll :0,
    communityChestJailCard: false,
    chanceJailCard: false,
  },

  {
    id: 2,
    name: 'Player 3',
    color: 'yellow',
    img: 'fas fa-hippo',
    controlledBy: 'ai',
    balance: 1500,
    position: 0,
    properties: [],
    inJail: false,
    doubleCount: 0,
    jailRoll :0,
    communityChestJailCard: false,
    chanceJailCard: false,
  },

  {
    id: 3,
    name: 'Player 4',
    color: 'green',
    img: 'fas fa-kiwi-bird',
    controlledBy: 'ai',
    balance: 1500,
    position: 0,
    properties: [],
    inJail: false,
    doubleCount: 0,
    jailRoll :0,
    communityChestJailCard: false,
    chanceJailCard: false,
  }
];

export const diceData = {
  die0: 1,
  die1: 1,
  areDiceRolled: false,
};

export const squareData = [
  {
    id: 0,
    name: 'Go',
    priceText: 'COLLECT $200 SALARY AS YOU PASS.',
    price: 0,
    color: '#f50c2b',
    colorBarClass: '',
    propertyClass: 'space corner go',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 1,
    name: 'Mediterran Avenue',
    priceText: '$60',
    price: 60,
    color: '#5e3577',
    colorBarClass: 'color-bar dark-purple',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 3,
    baseRent: 2,
    rent1: 10,
    rent2: 30,
    rent3: 90,
    rent4: 160,
    rent5: 2500,
    housePrice: 50,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 2,
    name: 'Community Chest',
    priceText: 'Follow instructions on top card',
    price: 0,
    color: 'grey',
    colorBarClass: '',
    propertyClass: 'space community-chest',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 3,
    name: 'Baltic Avenue',
    priceText: '$50',
    price: 50,
    color: '#5e3577',
    colorBarClass: 'color-bar dark-purple',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 3,
    baseRent: 4,
    rent1: 20,
    rent2: 60,
    rent3: 180,
    rent4: 320,
    rent5: 450,
    housePrice: 50,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 4,
    name: 'Income Tax',
    priceText: '$200',
    price: 0,
    color: '#41994e',
    colorBarClass: '',
    propertyClass: 'space fee income-tax',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 5,
    name: 'Reading Railroad',
    priceText: '$200',
    price: 200,
    color: '#cc6fcc',
    colorBarClass: '',
    propertyClass: 'space railroad',
    owner: '',
    ownerID: -1,
    group: 1,
    baseRent: 25,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: 'drawing fa fa-subway', 
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 6,
    name: 'Oriental Avenue',
    priceText: '$100',
    price: 100,
    color: '#d2eaf5',
    colorBarClass: 'color-bar light-blue',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 4,
    baseRent: 6,
    rent1: 30,
    rent2: 90,
    rent3: 270,
    rent4: 400,
    rent5: 550,
    housePrice: 50,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 7,
    name: 'Chance',
    propertyClass: 'space chance',
    price: 0,
    priceText: '',
    color: '#f50c2b',
    colorBarClass: '',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 8,
    name: 'Vermont Avenue',
    priceText: '$100',
    price: 100,
    color: '#d2eaf5',
    colorBarClass: 'color-bar light-blue',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 4,
    baseRent: 6,
    rent1: 30,
    rent2: 90,
    rent3: 270,
    rent4: 400,
    rent5: 550,
    housePrice: 50,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 9,
    name: 'Connecticut Avenue',
    priceText: '$120',
    price: 120,
    color: '#d2eaf5',
    colorBarClass: 'color-bar light-blue',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 4,
    baseRent: 8,
    rent1: 40,
    rent2: 100,
    rent3: 300,
    rent4: 450,
    rent5: 600,
    housePrice: 50,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 10,
    name: 'Just Visiting',
    priceText: '',
    price: 0,
    color: '#fa811d',
    colorBarClass: '',
    propertyClass: 'space corner jail',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 11,
    name: 'St. Charles Place',
    priceText: '$140',
    price: 140,
    color: '#b02f7c',
    colorBarClass: 'color-bar purple',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 5,
    baseRent: 10,
    rent1: 50,
    rent2: 150,
    rent3: 450,
    rent4: 625,
    rent5: 750,
    housePrice: 100,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 12,
    name: 'Electric Company',
    priceText: '$150',
    price: 150,
    color: '#ffed20',
    colorBarClass: '',
    propertyClass: 'space utility electric-company',
    owner: '',
    ownerID: -1,
    group: 2,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: 'drawing fa fa-lightbulb',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 13,
    name: 'States Avenue',
    priceText: '$140',
    price: 140,
    color: '#b02f7c',
    colorBarClass: 'color-bar purple',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 5,
    baseRent: 10,
    rent1: 50,
    rent2: 150,
    rent3: 450,
    rent4: 625,
    rent5: 750,
    housePrice: 100,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 14,
    name: 'Virginia Avenue',
    priceText: '$160',
    price: 160,
    color: '#b02f7c',
    colorBarClass: 'color-bar purple',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 5,
    baseRent: 12,
    rent1: 60,
    rent2: 180,
    rent3: 500,
    rent4: 700,
    rent5: 900,
    housePrice: 100,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 15,
    name: 'Pennsylvania Railroad',
    priceText: '$200',
    price: 200,
    color: '#cc6fcc',
    colorBarClass: '',
    propertyClass: 'space railroad',
    owner: '',
    ownerID: -1,
    group: 1,
    baseRent: 25,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 100,
    isMortgaged: false,
    icon: 'drawing fa fa-subway',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 16,
    name: 'St. James Avenue',
    priceText: '$180',
    price: 180,
    color: '#fa811d',
    colorBarClass: 'color-bar orange',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 6,
    baseRent: 14,
    rent1: 70,
    rent2: 200,
    rent3: 550,
    rent4: 750,
    rent5: 950,
    housePrice: 100,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 17,
    name: 'Community Chest',
    priceText: 'Follow instructions on top card',
    price: 0,
    color: 'grey',
    colorBarClass: '',
    propertyClass: 'space community-chest',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 18,
    name: 'Tennessee Avenue',
    priceText: '$180',
    price: 180,
    color: '#fa811d',
    colorBarClass: 'color-bar orange',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 6,
    baseRent: 14,
    rent1: 70,
    rent2: 200,
    rent3: 500,
    rent4: 750,
    rent5: 950,
    housePrice: 100,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 19,
    name: 'New York Avenue',
    priceText: '$200',
    price: 200,
    color: '#fa811d',
    colorBarClass: 'color-bar orange',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 6,
    baseRent: 16,
    rent1: 80,
    rent2: 220,
    rent3: 600,
    rent4: 800,
    rent5: 1000,
    housePrice: 100,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 20,
    name: 'Free Parking',
    priceText: '',
    price: 0,
    color: '#f50c2b',
    colorBarClass: '',
    propertyClass: 'space corner free-parking',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 21,
    name: 'Kentucky Avenue',
    priceText: '$220',
    price: 220,
    color: '#f50c2b',
    colorBarClass: 'color-bar red',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 7,
    baseRent: 18,
    rent1: 90,
    rent2: 250,
    rent3: 700,
    rent4: 875,
    rent5: 1050,
    housePrice: 150,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 22,
    name: 'Chance',
    priceText: '',
    price: 0,
    color: '#f50c2b',
    colorBarClass: '',
    propertyClass: 'space chance',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 23,
    name: 'Indiana Avenue',
    priceText: '$220',
    price: 220,
    color: '#f50c2b',
    colorBarClass: 'color-bar red',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 7,
    baseRent: 18,
    rent1: 90,
    rent2: 250,
    rent3: 700,
    rent4: 875,
    rent5: 1050,
    housePrice: 150,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 24,
    name: 'Illinois Avenue',
    priceText: '$200',
    price: 200,
    color: '#f50c2b',
    colorBarClass: 'color-bar red',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 7,
    baseRent: 20,
    rent1: 100,
    rent2: 300,
    rent3: 750,
    rent4: 925,
    rent5: 1100,
    housePrice: 150,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 25,
    name: 'B & O Railroad',
    priceText: '$200',
    price: 200,
    color: '#cc6fcc',
    colorBarClass: '',
    propertyClass: 'space railroad',
    owner: '',
    ownerID: -1,
    group: 1,
    baseRent: 25,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: 'drawing fa fa-subway',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 26,
    name: 'Atlantic Avenue',
    priceText: '$260',
    price: 260,
    color: '#ffed20',
    colorBarClass: 'color-bar yellow',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 8,
    baseRent: 22,
    rent1: 110,
    rent2: 330,
    rent3: 800,
    rent4: 975,
    rent5: 1150,
    housePrice: 150,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 27,
    name: 'Ventnor Avenue',
    priceText: '$260',
    price: 260,
    color: '#ffed20',
    colorBarClass: 'color-bar yellow',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 8,
    baseRent: 22,
    rent1: 100,
    rent2: 330,
    rent3: 800,
    rent4: 975,
    rent5: 1150,
    housePrice: 150,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 28,
    name: 'Waterworks',
    priceText: '$120',
    price: 120,
    color: '#5a6dba',
    colorBarClass: '',
    propertyClass: 'space utility waterworks',
    owner: '',
    ownerID: -1,
    group: 2,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: 'drawing fa fa-tint',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 29,
    name: 'Marvin Gardens',
    priceText: '$280',
    price: 280,
    color: '#ffed20',
    colorBarClass: 'color-bar yellow',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 8,
    baseRent: 24,
    rent1: 120,
    rent2: 360,
    rent3: 850,
    rent4: 1025,
    rent5: 1200,
    housePrice: 150,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 30,
    name: 'Go To Jail',
    priceText: '',
    price: 0,
    color: '#640303',
    colorBarClass: '',
    propertyClass: 'space corner go-to-jail',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 31,
    name: 'Pacific Avenue',
    priceText: '$300',
    price: 300,
    color: '#41994e',
    colorBarClass: 'color-bar green',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 9,
    baseRent: 26,
    rent1: 130,
    rent2: 390,
    rent3: 900,
    rent4: 1100,
    rent5: 1275,
    housePrice: 200,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 32,
    name: 'North Carolina Avenue',
    priceText: '$300',
    price: 300,
    color: '#41994e',
    colorBarClass: 'color-bar green',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 9,
    baseRent: 26,
    rent1: 130,
    rent2: 390,
    rent3: 900,
    rent4: 1100,
    rent5: 1275,
    housePrice: 200,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 33,
    name: 'Community Chest',
    priceText: 'Follow instructions on top card',
    price: 0,
    color: 'grey',
    colorBarClass: '',
    propertyClass: 'space community-chest',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 34,
    name: 'Pennsylvania Avenue',
    priceText: '$320',
    price: 320,
    color: '#41994e',
    colorBarClass: 'color-bar green',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 9,
    baseRent: 28,
    rent1: 150,
    rent2: 450,
    rent3: 1000,
    rent4: 1200,
    rent5: 1400,
    housePrice: 200,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 35,
    name: 'Short Line',
    priceText: '$200',
    price: 200,
    color: '#cc6fcc',
    colorBarClass: '',
    propertyClass: 'space railroad',
    owner: '',
    ownerID: -1,
    group: 1,
    baseRent: 25,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: 'drawing fa fa-subway',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 36,
    name: 'Chance',
    priceText: '',
    price: 0,
    color: '#f50c2b',
    colorBarClass: '',
    propertyClass: 'space chance',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 37,
    name: 'Park Place',
    priceText: '$350',
    price: 350,
    color: '#5a6dba',
    colorBarClass: 'color-bar dark-blue',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 10,
    baseRent: 35,
    rent1: 175,
    rent2: 500,
    rent3: 1100,
    rent4: 1300,
    rent5: 1500,
    housePrice: 200,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 38,
    name: 'Luxury Tax',
    priceText: '$75',
    price: 0,
    color: '#5e3577',
    colorBarClass: '',
    propertyClass: 'space fee luxury-tax',
    owner: '',
    ownerID: -1,
    group: 0,
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },

  {
    id: 39,
    name: 'Boardwalk',
    priceText: '$400',
    price: 400,
    color: '#5a6dba',
    colorBarClass: 'color-bar dark-blue',
    propertyClass: 'space property',
    owner: '',
    ownerID: -1,
    group: 10,
    baseRent: 50,
    rent1: 200,
    rent2: 600,
    rent3: 1400,
    rent4: 1700,
    rent5: 2000,
    housePrice: 200,
    isMortgaged: false,
    icon: '',
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 40,
    name: `Get Out of Jail C' Chest Card`,
    color: 'black',
    owner: '',
    ownerID: -1,
    group: 0,
    icon: '',
    priceText: '',
    price: 0,
    colorBarClass: '',
    propertyClass: '',
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  },
  {
    id: 41,
    name: 'Get Out of Jail Chance Card',
    color: 'black',
    owner: '',
    ownerID: -1,
    group: 0,
    icon: '',
    priceText: '',
    price: 0,
    colorBarClass: '',
    propertyClass: '',
    baseRent: 0,
    rent1: 0,
    rent2: 0,
    rent3: 0,
    rent4: 0,
    rent5: 0,
    housePrice: 0,
    isMortgaged: false,
    houseCount: 0,
    hotelCount: 0,
    doubleRent: false,
  }
];

export const chanceCardData = [
  'Get out of Jail, Free. This card may be kept until needed or sold.',
  'Make General Repairs on All Your Property. For each house pay $25. For each hotel $100.',        
  'Speeding fine $15.',       
  'You have been elected chairman of the board. Pay each player $50.',       
  'Go back three spaces.',       
  'ADVANCE TO THE NEAREST UTILITY.',       
  'Bank pays you dividend of $50.',        
  'ADVANCE TO THE NEAREST RAILROAD.',        
  'Pay poor tax of $15.',       
  `Take a trip to Reading Rail Road. If you pass 'GO' collect $200.`,       
  'ADVANCE to Boardwalk.',        
  `ADVANCE to Illinois Avenue. If you pass 'GO' collect $200.`,       
  'Your building loan matures. Collect $150.',       
  `ADVANCE to a random space. If you pass 'GO' collect $200.`,       
  `ADVANCE to St. Charles Place. If you pass 'GO' collect $200.`,       
  `Go to Jail. Go Directly to Jail. Do not pass 'GO'. Do not collect $200.`
];

export const communityChestCardData = [
  'Get out of Jail, Free. This card may be kept until needed or sold.',        
  'You have won second prize in a beauty contest. Collect $10.',        
  'From sale of stock, you get $50.',        
  'Life insurance matures. Collect $100.',        
  'Income tax refund. Collect $20.',       
  'Holiday fund matures. Receive $100.',        
  'You inherit $100.',        
  'Receive $25 consultancy fee.',        
  'Pay hospital fees of $100.',        
  'Bank error in your favor. Collect $200.',        
  'Pay school fees of $50.',        
  `Doctor's fee. Pay $50.`,        
  'It is your birthday. Collect $10 from every player.',        
  `Advance to 'GO' (Collect $200).`,        
  'You are assessed for street repairs. $40 per house. $115 per hotel.',        
  `Go to Jail. Go directly to Jail. Do not pass 'GO'. Do not collect $200.`        
];



